### ISSUE TITLE
other.getFields().hasOwnProperty is not function

### ISSUE THREAD

**Issue by lalalic** [jarwol/graphql-schema-utils#4] opened 2017-09-04 08:41 UTC
when merging, I got the problem. it seems other.getFields() has no Object.prototype. It works with replacing it with Object.prototype.hasOwnProperty.call(other.getFields(), key)

**Comment by Tyratox** [comment] 2017-09-06 17:43
Same problem here. @lalalic's solution works for me as well.

**Comment by jarwol** [comment] 2017-09-06 17:51
@lalalic and @Tyratox - Can one or both of you provide a little more context? Is this an error happening within the module itself? If so, can you provide a stack trace and/or a way to reproduce? Thanks!

**Comment by Tyratox** [comment] 2017-09-06 20:38
Yeah sure, I'll post a stack trace and an easy way to reproduce this error tomorrow.

**Comment by Tyratox** [comment] 2017-09-07 16:25
So this is the stack trace:

    TypeError: other.getFields(...).hasOwnProperty is not a function
    GraphQLObjectType.mergeObjectTypes [as merge] (node_modules/graphql-schema-utils/index.js:510:31)
    ....

(https://github.com/jarwol/graphql-schema-utils/blob/master/index.js#L510)

First I felt like to the problem was me not passing an object but it was in fact an object that was passed to the merge function. As @lalalic mentioned, this happens if the object doesn't inherit from `Object.prototype`.
The following (shortened) code throws said error.

    const {
        GraphQLObjectType,
        GraphQLString,
    } = require("graphql");

    require("graphql-schema-utils");

    let type = new GraphQLObjectType({
        name: "type",
        fields: {
            name: {
                type: GraphQLString
            }
        }
    });
            
    let type2 = type.merge(new GraphQLObjectType({
        name: "type",
        fields: {
            name2: {
                type: GraphQLString
            }
        }
    }));

From my understanding of the source code, the `other.getFields().hasOwnProperty(key)` could be removed completely as `Object.keys` "returns an array of a given object's own enumerable properties" (https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object/keys) but I could be missing something.

Anyway, I hope at least some of this will help figuring out whats wrong

Here's the sample file:
[test.zip](https://github.com/jarwol/graphql-schema-utils/files/1285389/test.zip)

**Comment by Tyratox** [comment] 2017-09-07 19:03
Interestingly enough `console.log(Object.keys(graphQlType))` logs

`[ 'name',
  'description',
  'astNode',
  'extensionASTNodes',
  'isTypeOf',
  '_typeConfig' ]`

which does not contain the key `_fields`.

But `graphQl._typeConfig` contains it (without an underscore), as well as `name`, `description`.
I'm not sure what's going on, https://github.com/graphql/graphql-js/blob/master/src/type/definition.js#L434 shows a `_fields` key.

**Comment by Tyratox** [comment] 2017-09-07 19:16
Okay `_fields` is not set until `getFields` is called.

    getFields(): GraphQLFieldMap<*, *> {
        return this._fields || (this._fields =
            defineFieldMap(this, this._typeConfig.fields)
        );
    }
(https://github.com/graphql/graphql-js/blob/master/src/type/definition.js#L453)

In other words `mergedType._fields[key] = other.getFields()[key];` (https://github.com/jarwol/graphql-schema-utils/blob/master/index.js#L511) won't work as expected if `getFields` isn't called in advance.

~~`mergedType._fields = mergedType._fields ? mergedType._fields : {};` would also be a possible solution.~~

~~Removing the check and adding the line mentioned above solves the problem for me.~~

getField sets the `_field` value based on `typeConfig.fields` which is most probably not empty!

**Closed as completed** 2017-09-09 14:57 UTC

**Comment by jarwol** [comment] 2017-09-09 15:01
Thanks, @Tyratox. Fix has been merged and new package published to npm.

**Comment by Tyratox** [comment] 2017-09-09 17:49
Cool, thanks! :)
